Grzegorz ocypa patch 2
grzegorz-ocypa/intro-html pull request #10
Opened 2019-12-11 15:23 UTC by grzegorz-ocypa

dodalem kod

2019-12-11 15:23 UTC, grzegorz-ocypa commented
?

2019-12-11 15:24 UTC, grzegorz-ocypa commented
/

2019-12-20 20:24 UTC, mirkosoft requested changes
Obie listy, które dodałeś (`ol` i `ul`) powinny być przed domknięciem znacznika `</body>`

2020-01-22 16:34 UTC, mirkosoft approved these changes
OK Grzesiu!

2020-01-22 16:35 UTC, merged